---
title: "Bonus!"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

This page contains links to journal articles, blog posts, webpages, etc., that we (the instructors) believe may be useful to you, or at the very least interesting. **Bold** articles are ones that we consider **must-reads** but don't have enough time to actually assign.

# Going deeper

This section contains materials that will help you understand the material covered at a deeper level. Use this section if you're feeling confused about the material covered or if you want to really cement the core concepts.

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Cronback & Meehl (1955) ["Construct validity in psychological tests"](readings/Cronbach_Meehl_1955.pdf)**                                                                                                | Article         | Construct Validity                                           | This used to be assigned in this class, which should tell you just how much I love it. It's an article that gets better with every subsequent reading. It's also enormously important, as it provides one of the foundations for measurement (rightly or wrongly) in psychological science.                                                                                                                                                                                             |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Malone & Goldstone (2019) ["Episode 936: The Modal American."](https://www.npr.org/2019/08/28/755191639/episode-936-the-modal-american)                                                                    | Podcast episode | Central tendency                                             | This episode of NPR's podcast, *Planet Money*, is a great discussion of what we mean when we say "average," why the mean can be a bad measure of central tendency, and how complicated calculating simple statistics are. They don't use the words "artifact" or "collinearity", but they discuss both and how they can lead to bad answers.                                                                                                                                            |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Simms (2008) ["Classical and Modern Methods of Psychological Scale Construction"](readings/Simms_2008.pdf)**                                                                                             | Article         | Construct Validity/Scale development                         | This is a great process article about how to build scales with good construct validity.                                                                                                                                                                                                                                                                                                                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Chester & Lasko (2019) ["Construct Validation of Experimental Manipulations in Social Psychology: Current Practices and Recommendations for the Future."](https://psyarxiv.com/t7ev9)                      | Article         | Construct Validity                                           | A preprint about construct validity in social psychology. They do a great job of explaining different kinds of validity in addition to empirically describing the extent to which social psychologists check for construct validity. Here is a lovely quote: "In the context of archery, construct validity is the practice of checking that the arrow hit the bullseye and internal validity is the practice of preventing the wind and your own breathing from influencing your aim." |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gucciardi & Gordon (2008)                                                                                                                                                                                  | Article         | Scale development                                            | An example of how to use interviews and qualitative methods to define a constructs and build a scale.                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                            |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| ["Personal construct psychology and the research interview"](readings/Gucciardi_2008.pdf)                                                                                                                  |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Dragostinov et al. (2022)                                                                                                                                                                                  | Article         | Scale development                                            | The Delphi method relies on a panel of experts to evaluate questionnaire items.                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                            |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| ["Preliminary psychometric scale development using the mixed methods Delphi technique"](readings/Dragostinov_2022.pdf)                                                                                     |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Salsman et al. (2018)                                                                                                                                                                                      | Article         | Scale development                                            | Another example of the use of qualitative research for building scales.                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                            |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| ["Refining and supplementing candidate measures of psychological well-being for the NIH PROMIS®: qualitative results from a mixed cancer sample"](readings/Salsman_2018.pdf)                               |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Simulation on the Rice Virtual Lab in Statistics](https://onlinestatbook.com/stat_sim/sampling_dist/)                                                                                                     | Website         | Sampling Distributions                                       | See a population, take a sample. Or take 5 samples. Or 10,000. Build your sampling distribution by hand. Compare sampling distributions with different sample sizes. See how the population distribution changes the sampling distribution.                                                                                                                                                                                                                                             |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Confidence Interval Demo](https://rpsychologist.com/d3/ci/) by Kristoffer Magnusson                                                                                                                       | Website         | Sampling Distributions and Confidence Intervals              | Respect sampling variability! This demo shows that not only does the mean change with each sample, but so does the width of the confidence interval (gasp!). But seriously, spend some time on this site. It will change the way you see statistics, literally speaking.                                                                                                                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fry (2019) ["What statistics can and can't tell us about ourselves."](https://www.newyorker.com/magazine/2019/09/09/what-statistics-can-and-cant-tell-us-about-ourselves)                                  | News article    | Probability                                                  | This article in the \*New Yorker\* explains issues of (frequentist) probability in terms you can explain to your grandma, as well as makes clear the issues of the Fisher tradition of reducing experiments to p-values.                                                                                                                                                                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Resnick (2017) ["What a nerdy debate about p-values shows about science -- and how to fix it."](https://www.vox.com/science-and-health/2017/7/31/16021654/p-values-statistical-significance-redefine-0005) | News article    | p-values and open science                                    | Another great article, this time on *Vox*, about p-values                                                                                                                                                                                                                                                                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Ioannidis (2005) ["Why most published findings are false."](readings/Ioannidis_2005.pdf)**                                                                                                               | Article         | p-values                                                     | This is one of the articles that kick-started the concern over p-values and the credibility revolution.                                                                                                                                                                                                                                                                                                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Bem (2011) ["Feeling the future: Experimental evidence for anomalous retroactive influences on cognition and affect."](readings/Bem_2011.pdf)**                                                          | Article         | ESP (but read it for context about p-values)                 | It's true, ESP is real. Or is it? What (if anything) in this article makes you skeptical of the results? Try to articulate the weaknesses.                                                                                                                                                                                                                                                                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Bem (2004) ["Writing the empirical journal article."](readings/Bem_2004.pdf)**                                                                                                                           | Article         | Writing (but really, read it for the discussion of analysis) | This was assigned to me when I was a graduate student. Some of the advice is actually very good, although most of the best stuff can be found in Strunk and White. The part of this article that's really worth reading is the "Analyzing Data" and "Reporting the Findings" subsections of "Planning your article."                                                                                                                                                                    |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Szollosi et al. (2019). ["Preregistration is redundant, at best."](https://psyarxiv.com/x36pz/)                                                                                                            | Preprint        | Preregistration                                              | Here's a counter argument, very well done!                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Anonymous et al. (2021). [Evidence of Fraud in an Influential Field Experiment about Dishonesty](http://datacolada.org/98)                                                                                 | Blog post       | Fraud and descriptive statistics                             | This is not only a case study of the issues of fraud in psychology, but it also serves as an excellent example of how examining descriptive statistics and distributions can reveal a lot about data.                                                                                                                                                                                                                                                                                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Hobbes & Gordon (2021).                                                                                                                                                                                    | Podcast episode | Questionable research pratices                               | The story of Brian Wansink, a nutrition researcher whose work was discovered to be filled with p-hacking, misconduct, and generally poor science.                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                            |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| "School lunches, p-hacking, and the original Pizzagate."                                                                                                                                                   |                 |                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

# Advanced Statistics

Are you ready to explore new topics? Here are some great resources for advanced statistical topics that we think are of broad interest.

|  |  |  |  |
|----|----|----|----|
| Lord (1953) ["On the statistical treatment of football numbers."](readings/Lord_1953.pdf) | Article | Numbers don't know where they came from. | This one is worth reading several times, ideally with a friend. Don't worry, it's quite short. A small note: "Tchebycheff" is sometimes written as "Chebyshev" and in either case is pronounced Cheb-ee-sheve. |
| Cox (1980) ["The optimal number of response alternatives for a scale: A review"](https://www.jstor.org/stable/pdf/3150495.pdf?casa_token=pnuy8XQLHTIAAAAA:QOUc17Ic0cquCBXuqyRvfCSBUiXkFwDoVjuOxHB8qjJHtyJXGSlam7Zxcd2RIABVOXMy-YARHJ6dHhuGc_ABJaTBk8Lf8FLF9EKX9wlrn99yB5CWPgg) | Article | Measurement | For those developing new measures, it's worth spending some time reading about psychometrics. As with everything, there's no one-size-fits-all answer to how many response options, whether to include a midpoint, and how to label your scales. But you should understand the implications of these choices before you write your own items. |
| Rohrer (2019) ["Indirect Effect Ex Machina."](http://www.the100.ci/2019/10/03/indirect-effect-ex-machina) | Blog | Mediation | Come for the ice cream and sauerkraut, stay for the creeping dread that many mediation studies are probably wrong. |

# `R`

Ready to do more with `R`? Of course you are.

|  |  |  |
|----|----|----|
| Peters (2004) ["The Zen of Python."](https://www.python.org/dev/peps/pep-0020/) | Coding principles | A list of 19 principles for writing better Python code; the principles also apply to writing better `R` code. |
| [Cheatsheets](https://rstudio.com/resources/cheatsheets/) | tidyverse | These are super useful for working with the `tidyverse` suite of packages. Functions are neatly described and even illustrated. |
| Hill (2019) ["Meet xaringan."](https://arm.rbind.io/slides/xaringan.html#1) | Slides | There are a ton of resource for learning how to make slides using `R`. Too many to list here. I like this one because it's accessible, funny, visually appealing, and will help you make slides that you're proud of. (By the way, UO has theme you can use.) |
| [Quarto Guide](https://quarto.org/docs/presentations/) | Slides (but also other documents and websites) | Slightly different from `xaringan` and `knitr`, but there's reason to think this may be more flexible in the future. |
| Mock (2022) [Quarto Workshop](https://www.youtube.com/watch?v=yvi5uXQMvu4) | Quarto | If you like Quarto, here's a workshop that shows you a lot you can do with it. |
| Bryan (2019?) ["Happy Git with R."](https://happygitwithr.com) | Git/Github | Interested in using GitHub for version control? Jenny Bryan will guide you through the process and metaphorically hand you a tissue when you're screaming with frustration. |
| Beck (2018?) [Intro to purrr](https://emoriebeck.github.io/R-tutorials/purrr/) | Iteration | Tutorial for the `purrr` package from the `tidyverse` suite. Very useful if you need to repeat something multiple times in a dataset. |
| [R project handout](./labs/r-project-handout.html) | R Project | Handouts for organizing r script and data within a R project. |
