---
title: "Syllabus"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

# Weekly schedule

LSR readings can be found in the free, online textbook, [*Learning Statistics with R*](https://learningstatisticswithr-bookdown.netlify.com/index.html) by Danielle Navarro. For those interested in taking notes, I recommend the use of the [Hypothes.is](http://Hypothes.is) app to annotate webpages. I will note that the formatting of the book online is wonky in a few places. If this bothers you, or you prefer to work offline, you can download a [PDF version](https://learningstatisticswithr.com/lsr-0.6.pdf) of the book.

| Week   | Date  | Topic                                  | Readings                                                                                                                                                                                                                                                                                                                                                  | Quiz   | Homework          |
|--------|-------|:---------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|-------------------|
| 1      | 09/27 | Introduction and overview              | LSR Ch 1 & 3                                                                                                                                                                                                                                                                                                                                              |        |                   |
| \-     | 09/29 | Research methods                       | LSR CH 2 & 4, [Rothman et al. (2013)](readings/Rothman_2013.pdf)[^1]                                                                                                                                                                                                                                                                                      |        |                   |
| \-     | 09/30 | *Lab: Introduction to R*               |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 2      | 10/04 | Latent variables and psychometrics     | Podcast: [Quantitude, S2E21 -- Yes, Virginia... There ARE Latent Variables](https://quantitudepod.org/listen/) (Make sure you scroll down to the correct episode) [CC available here](https://uoregon.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9e5c5f9e-666b-4741-875b-adba015e9ded)., [Bringmann et al., 2022,](readings/bringmann_etal_2022.pdf) | Quiz 1 |                   |
| \-     | 10/06 | Describing data                        | LSR Ch 5 & 6                                                                                                                                                                                                                                                                                                                                              |        |                   |
| \-     | 10/07 | *Lab: R basics and descriptives*       |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 3      | 10/11 | Describing data                        | [Ozer & Funder (2019)](readings/Ozer_Funder_2019.pdf)                                                                                                                                                                                                                                                                                                     | Quiz 2 |                   |
| \-     | 10/13 | Probability                            | LSR Intro to Part IV and Ch 9.1-9.3, [Wetzels et al. (2011)](readings/Wetzels_etal_2011.pdf)                                                                                                                                                                                                                                                              |        |                   |
| \-     | 10/14 | *Lab: Functional programming*          |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 4      | 10/18 | Probability                            | LSR Ch 9.4                                                                                                                                                                                                                                                                                                                                                | Quiz 3 |                   |
| \-     | 10/20 | Probability                            | LSR Ch 9.5-9.6                                                                                                                                                                                                                                                                                                                                            |        |                   |
| \-     | 10/21 | *Lab: Probability distributions*       |                                                                                                                                                                                                                                                                                                                                                           |        | HW 1 Due          |
| 5      | 10/25 | Sampling                               | LSR Ch 10                                                                                                                                                                                                                                                                                                                                                 | Quiz 4 |                   |
| \-     | 10/27 | Hypothesis testing                     | LSR Ch 11                                                                                                                                                                                                                                                                                                                                                 |        |                   |
| \-     | 10/28 | *Lab: Data wrangling*                  |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 6      | 11/01 | Hypothesis testing                     | [Sainani (2012)](readings/Sainani_2012.pdf)                                                                                                                                                                                                                                                                                                               | Quiz 5 |                   |
| \-     | 11/03 | Hypothesis testing                     |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| \-     | 11/04 | *Lab: Graphing with ggplot2*           |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 7      | 11/08 | Critiques of hypothesis testing        | [Simmons et al. (2011)](readings/Simmons_etal_2011.pdf) [Cumming (2014)](readings/Cumming_2014.pdf)                                                                                                                                                                                                                                                       | Quiz 6 |                   |
| \-     | 11/10 | Open Science and Wrap-up               | [Five Thirty Eight](https://fivethirtyeight.com/features/science-isnt-broken/)                                                                                                                                                                                                                                                                            |        |                   |
| \-     | 11/11 | *Lab: No Lab*                          |                                                                                                                                                                                                                                                                                                                                                           |        | HW 2 Due          |
| 8      | 11/15 | One-sample tests                       | LSR Ch 13.1-13.2                                                                                                                                                                                                                                                                                                                                          | Quiz 7 |                   |
| \-     | 11/17 | Comparing two means (paired)           | LSR Ch 13.3-13.11                                                                                                                                                                                                                                                                                                                                         |        |                   |
| \-     | 11/18 | *Lab: One- and paired-samples t-tests* |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 9      | 11/22 | Something different: RMarkdown         |                                                                                                                                                                                                                                                                                                                                                           | Quiz 8 |                   |
| \-     | 11/24 | **Thanksgiving**                       |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| \-     | 11/25 | *Lab: No Lab*                          |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| 10     | 11/29 | Comparing two means (independent)      |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| \-     | 12/01 | Effect sizes and assumptions           |                                                                                                                                                                                                                                                                                                                                                           | Quiz 9 |                   |
| \-     | 12/02 | *Lab: Independent samples t-tests*     |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| Finals | 12/05 |                                        |                                                                                                                                                                                                                                                                                                                                                           |        |                   |
| \-     | 12/07 |                                        |                                                                                                                                                                                                                                                                                                                                                           |        | HW 3 Due [^2] 9am |

[^1]: There are several great commentaries on this article that I would encourage you to read. They are: - [Richiardi et al. (2013).](readings/Richiardi_2013.pdf) Representativeness is usually not necessary and often should be avoided. - [Nohr et al. (2013).](readings/Nohr_2013.pdf) Epidemiologists have debated representativeness for more than 40 years---has the time come to move on? - [Elwood (2013).](readings/Elwood_2013.pdf) On representativeness - [Ebrahim et al. (2013).](readings/Ebrahim_2013.pdf) Should we always deliberately be non-representative?

[^2]: Final grades are due the following Tuesday, so there are limited opportunities to redo this particular assignment for points. I will do my best to grade these within 24 hours of receipt so you have a chance to retry any missed points. Consider Friday 12/9 at 9am PT the last possible time to submit this assignment.

**Final:** Oral exam will take place the week of December 5.

# Graded materials

Your final grade is comprised of three components:

-   Quizzes: 35%
-   Homework: 40%
-   Journal entries: 5%
-   Oral exam: 20%

## Quizzes

Quizzes are intended to assess your understanding of the theoretical principles underlying statistics. There will be a quiz every Tuesday, with the exception of the first week, when there will be no quiz, and the final week when the quiz will be on Thursday.

Quizzes may be resubmitted with corrections and receive full credit. To resubmit a quiz, write your corrections on the back of the quiz; for each question that was answered incorrectly, identify the correct answer, and explain why this is the correct answer. Only if the explanation sufficiently conveys an understanding of the theoretical principles will credit be given. There are no limits to the number of times a quiz may be resubmitted.

If you are absent the day of a quiz, you can take a make-up quiz after the next lecture you attend.

## Homework assignments

Homework assignments are intended to gauge your ability to apply the topics covered in class to the practice of data analysis. Homework assignments are to be done using R and RMarkdown; completed assignments should be submitted through Canvas, and students must attach both the .Rmd file and the compiled HTML file.

Homework assignments are due at the time the first lab starts on the day the assignment is listed. Homework assignments may be resubmitted with corrections and receive full credit. Please note, however, that corrections can only be made to problems that were answered at initial submission. There is no limit to the number of times a homework assignment may be resubmitted.

Late assignments will receive 50% of the points earned. For example, if you correctly answer questions totalling 28 points, the assignment will receive 14 points. If you resubmit this assignment with corrected answers (a total of 30 points), the assignment will receive 15 points. Late assignments will be accepted only within 7 days of the original deadline.

You may discuss homework assignments with your classmates; however, it is important that you complete each assignment on your own and do not simply copy someone else's code. If I believe one student has copied another's work, both students will receive a 0 on the homework assignment and will not be allowed to resubmit the assignment for points.

## Journal entries

Each week you'll complete a short journal entry on Canvas. To earn full points, you'll have to write at least 200 words about anything at all. This can include content related to the course, such as how well you feel you understand the material or how you see the material come up in other work. This can also include anything related to your personal life or mental health that you would like for me to know, such as whether you are struggling to balance classes and research, having trouble creating a workspace at home, or whether you can balance time spent on campus and off. This can also be completely random things, like a news article you can't stop thinking about, or musings on the mist-downpour continuum of Oregon weather. The content of what you write has *no impact* on your grade. In addition, what you write will be kept confidential.

You may skip 2 journal entries with no penalty.

The purpose of this assignment is to help facilitate communication between you and me. I have used this assignment since Spring 2020 and found it an excellent way to build relationships with students. Plus, I found that many students were more comfortable discussing questions and concerns in their journal assignments rather than through email.

## Oral exam

The oral exam will take place during finals week. About two weeks prior, you will be asked to schedule a time to complete the exam. The exam will take roughly 15 minutes. You will be asked to explain basic and elemental concepts, as if you were teaching an advanced undergraduate or new graduate student.

# Materials needed

We will be using R for all data wrangling, visualization, and analysis. You may not use another statistical program in this course. Students must have the latest version of R, which can be downloaded [here](https://ftp.osuosl.org/pub/cran/). It is strongly recommended that students also download the RStudio GUI, available [here](https://www.rstudio.com/products/rstudio/download/#download). Both softwares are free.

All reading assignments will be posted online.

# Policies

**Cheating and plagiarism.** Any student caught cheating on an assignment, quiz, or exam will receive a 0 on that assignment. Frankly, you're in graduate school, and the purpose of work is to create opportunities to learn and improve. Even if cheating helps you in the short term, you'll quickly find yourself ill-prepared for the career you have chosen. If you find yourself tempted to cheat, please come speak to Dr. Weston about an extension and developing tools to improve your success.

**Students with special needs.** The UO works to create inclusive learning environments. If there are aspects of the instruction or design of this course that result in disability-related barriers to your participation, please notify me as soon as possible. You may also wish to contact Disability Services in 164 Oregon Hall at 541-346-1155 or [disabsrv\@uoregon.edu](mailto:disabsrv@uoregon.edu).

**COVID-19 related.** Masks are optional. Please be respectful of your peers' choices regarding masks. I (Sara) will be monitoring the university and county case counts and am prepared to update either the mask policy or the format of the course in response to rising cases. I will not be wearing a mask while lecturing in order to prioritize my being understood by students. We'll open windows whenever possible. Lectures will be recorded for students who would prefer more flexibility. If you are feeling unwell, please mask or stay home and use the recordings to keep up with the course.

# Basic needs

Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live and believes this may affect their performance in this course is urged to contact the Dean of Students Office (346-3216, 164 Oregon Hall) for support.

This UO web page includes resources for food, housing, health care, childcare, transportation, technology, finances, and legal support: <https://blogs.uoregon.edu/basicneeds/food/>
