---
title: "Lab 8: One-sample and Independent Samples t-tests"
output: 
  html_document: 
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: TRUE
---

```{r setup, include = FALSE}
# set chunk options
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

# suppress scientific notation
options(scipen = 999)

#load required packages
library(tidyverse) # includes dplyr and ggplot2 functions
library(gganimate) # allows the creation of gifs from ggplot2
library(lsr) # includes t-test functions
library(psych) # includes more t-test functions

# load data
data <- Garcia 
```

# Purpose

Today's lab will guide you through the process of conducting a [One-Sample t-test](#one) and an [Independent Samples t-test](#independent). For each test, we will first go through the process of conducting the tests using the arithmetic and probability distributions in R. Then we will compare and contrast the functions in the `{psych}` and `{lsr}` packages. 

To quickly navigate to the desired section, click one of the following links:

1. [One-Sample t-test](#one)
1. [Independent Samples t-test](#independent)
1. [Minihacks](#minihacks)

# The Data

Today we will be using data from Garcia, Schmitt, Branscombe, and Ellemers (2010) sexism study provided through the `{psych}` package. For see information about the dataset you can use `?Garcia`. In short, the `Garcia` data set measures an individuals reaction has a sample of `129` participants on `6` varaibles.


***

# The Grammar of Graphics {#grammar}


# Minihacks {#minihacks}

You are welcome to work with a partner or in a small group of 2-3 people. Please feel free to ask the lab leader any questions you might have!

The minihacks all use the `movies` data set from the `{yarrr}` package.

## Minihack 1: Histograms

1. Create a histogram of domestic and international revenue combined (`revenue.all`). Is it normally distributed?

